// Code generated by hzn; DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"m31labs.dev/horizon/capability"
)

const CapabilityManifestJSON = "{\n  \"schema\": \"m31labs.dev/horizon/capability/v1\",\n  \"package\": \"probes\",\n  \"programs\": [\n    {\n      \"name\": \"OnTCPInit\",\n      \"kind\": \"struct_ops\",\n      \"attach\": \"tcp_init\",\n      \"section\": \"struct_ops/tcp_init\",\n      \"capabilities\": [\n        \"kernel.network.tcp.congestion.mutate\"\n      ]\n    }\n  ],\n  \"capabilities\": [\n    {\n      \"name\": \"kernel.network.tcp.congestion.mutate\",\n      \"kind\": \"source\",\n      \"danger\": {\n        \"mode\": \"mutate\",\n        \"scope\": \"process\",\n        \"reversibility\": \"restart\"\n      },\n      \"program\": \"OnTCPInit\",\n      \"section\": \"struct_ops/tcp_init\",\n      \"maps\": {\n        \"read\": [],\n        \"write\": [],\n        \"events\": []\n      },\n      \"requirements\": {\n        \"min_kernel\": \"5.6\",\n        \"programs\": [\n          {\n            \"name\": \"struct_ops\",\n            \"min_kernel\": \"5.6\"\n          }\n        ],\n        \"permissions\": [\n          \"bpf_program_load\"\n        ],\n        \"features\": [\n          \"btf\",\n          \"struct_ops\"\n        ]\n      }\n    }\n  ],\n  \"maps\": [\n    {\n      \"name\": \"Ops\",\n      \"kind\": \"struct_ops\",\n      \"value\": \"tcp_congestion_ops\"\n    }\n  ],\n  \"requirements\": {\n    \"min_kernel\": \"5.6\",\n    \"programs\": [\n      {\n        \"name\": \"struct_ops\",\n        \"min_kernel\": \"5.6\"\n      }\n    ],\n    \"maps\": [\n      {\n        \"name\": \"struct_ops\",\n        \"min_kernel\": \"5.6\"\n      }\n    ],\n    \"permissions\": [\n      \"bpf_program_load\"\n    ],\n    \"features\": [\n      \"btf\",\n      \"struct_ops\"\n    ]\n  }\n}\n"

func CapabilityManifest() (capability.Manifest, error) {
	var manifest capability.Manifest
	if err := json.Unmarshal([]byte(CapabilityManifestJSON), &manifest); err != nil {
		return capability.Manifest{}, err
	}
	return manifest, nil
}

type Objects struct {
	Ops       *ebpf.Map     `ebpf:"Ops"`
	OnTCPInit *ebpf.Program `ebpf:"OnTCPInit"`
}

type LoadOptions struct {
	Collection    *ebpf.CollectionOptions
	RemoveMemlock bool
}

func LoadObjects(path string) (*Objects, error) {
	return LoadObjectsWithOptions(path, LoadOptions{RemoveMemlock: true})
}

func LoadObjectsWithOptions(path string, opts LoadOptions) (*Objects, error) {
	if opts.RemoveMemlock {
		if err := rlimit.RemoveMemlock(); err != nil {
			return nil, fmt.Errorf("remove memlock limit: %w", err)
		}
	}
	spec, err := ebpf.LoadCollectionSpec(path)
	if err != nil {
		return nil, fmt.Errorf("load %s: %w", path, err)
	}
	var objects Objects
	if err := spec.LoadAndAssign(&objects, opts.Collection); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}
	return &objects, nil
}

func (o *Objects) Close() error {
	if o == nil {
		return nil
	}
	var err error
	if o.Ops != nil {
		err = errors.Join(err, o.Ops.Close())
	}
	if o.OnTCPInit != nil {
		err = errors.Join(err, o.OnTCPInit.Close())
	}
	return err
}

func (o *Objects) findStructOpsMap() *ebpf.Map {
	if o == nil {
		return nil
	}
	if o.Ops != nil && o.Ops.Type() == ebpf.StructOpsMap {
		return o.Ops
	}
	return nil
}

// AttachOnTCPInit attaches the struct_ops map containing OnTCPInit to its kernel
// subsystem. struct_ops attach is per-map, not per-program — if multiple
// struct_ops programs share a map, attaching via any one of them attaches
// all of them. The returned Link controls the lifetime of the entire
// struct_ops registration; closing the Link detaches the map.
//
// Requires kernel >= 5.6 with BTF and CONFIG_BPF_STRUCT_OPS=y. The struct_ops
// map must be exposed on Objects as an *ebpf.Map field; if no such field is
// found at runtime, the method returns a sentinel error pointing at the
// missing map.
func (o *Objects) AttachOnTCPInit() (link.Link, error) {
	if o == nil || o.OnTCPInit == nil {
		return nil, fmt.Errorf("OnTCPInit program is not loaded")
	}
	m := o.findStructOpsMap()
	if m == nil {
		return nil, fmt.Errorf("no struct_ops map found for OnTCPInit; ensure the .bpf.o was loaded with its struct_ops map exposed on Objects")
	}
	return link.AttachStructOps(link.StructOpsOptions{Map: m})
}
