// Code generated by hzn; DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"m31labs.dev/horizon/capability"
)

const CapabilityManifestJSON = "{\n  \"schema\": \"m31labs.dev/horizon/capability/v0\",\n  \"package\": \"probes\",\n  \"programs\": [\n    {\n      \"name\": \"OnTCPInit\",\n      \"kind\": \"struct_ops\",\n      \"attach\": \"tcp_init\",\n      \"section\": \"struct_ops/tcp_init\",\n      \"capabilities\": [\n        \"kernel.network.tcp.congestion.mutate\"\n      ]\n    }\n  ],\n  \"capabilities\": [\n    {\n      \"name\": \"kernel.network.tcp.congestion.mutate\",\n      \"kind\": \"source\",\n      \"danger\": \"mutate\",\n      \"program\": \"OnTCPInit\",\n      \"section\": \"struct_ops/tcp_init\",\n      \"maps\": {\n        \"read\": [],\n        \"write\": [],\n        \"events\": []\n      },\n      \"requirements\": {\n        \"min_kernel\": \"5.6\",\n        \"programs\": [\n          {\n            \"name\": \"struct_ops\",\n            \"min_kernel\": \"5.6\"\n          }\n        ],\n        \"permissions\": [\n          \"bpf_program_load\"\n        ],\n        \"features\": [\n          \"btf\",\n          \"struct_ops\"\n        ]\n      }\n    }\n  ],\n  \"requirements\": {\n    \"min_kernel\": \"5.6\",\n    \"programs\": [\n      {\n        \"name\": \"struct_ops\",\n        \"min_kernel\": \"5.6\"\n      }\n    ],\n    \"permissions\": [\n      \"bpf_program_load\"\n    ],\n    \"features\": [\n      \"btf\",\n      \"struct_ops\"\n    ]\n  }\n}\n"

func CapabilityManifest() (capability.Manifest, error) {
	var manifest capability.Manifest
	if err := json.Unmarshal([]byte(CapabilityManifestJSON), &manifest); err != nil {
		return capability.Manifest{}, err
	}
	return manifest, nil
}

type Objects struct {
	OnTCPInit *ebpf.Program `ebpf:"OnTCPInit"`
}

type LoadOptions struct {
	Collection    *ebpf.CollectionOptions
	RemoveMemlock bool
}

func LoadObjects(path string) (*Objects, error) {
	return LoadObjectsWithOptions(path, LoadOptions{RemoveMemlock: true})
}

func LoadObjectsWithOptions(path string, opts LoadOptions) (*Objects, error) {
	if opts.RemoveMemlock {
		if err := rlimit.RemoveMemlock(); err != nil {
			return nil, fmt.Errorf("remove memlock limit: %w", err)
		}
	}
	spec, err := ebpf.LoadCollectionSpec(path)
	if err != nil {
		return nil, fmt.Errorf("load %s: %w", path, err)
	}
	var objects Objects
	if err := spec.LoadAndAssign(&objects, opts.Collection); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}
	return &objects, nil
}

func (o *Objects) Close() error {
	if o == nil {
		return nil
	}
	var err error
	if o.OnTCPInit != nil {
		err = errors.Join(err, o.OnTCPInit.Close())
	}
	return err
}

func (o *Objects) AttachOnTCPInit() (link.Link, error) {
	// struct_ops attach not yet supported by bindgen — see roadmap #9 follow-up.
	return nil, fmt.Errorf("struct_ops attach not yet supported by bindgen — see roadmap #9 follow-up")
}
