package main

import (
	"bufio"
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// LibbpfHelper is one entry parsed out of libbpf's bpf_helper_defs.h.
// Only the fields the candidate-generator needs are captured — return
// type, parameter list, and argument body are intentionally discarded.
type LibbpfHelper struct {
	// KernelSymbol is the exact identifier as written in the header
	// (e.g. "bpf_map_lookup_elem"). Always begins with the "bpf_" prefix
	// since that prefix is part of the header's declaration shape.
	KernelSymbol string

	// HelperID is the integer enum value cast on the right-hand side of
	// the declaration ("= (void *) <id>;"). Stable across libbpf
	// releases for established helpers.
	HelperID int
}

// helperDeclRegex matches the single line every BPF helper declaration
// resolves to in src/bpf_helper_defs.h. The header is auto-generated by
// libbpf's bpf_doc.py and every entry follows the exact same shape:
//
//	static <return-type> (* const bpf_<name>)(<params>) = (void *) <id>;
//
// optionally prefixed with an attribute (e.g. __bpf_fastcall). Multi-line
// declarations do not occur in any pinned libbpf release we've surveyed.
//
// Capture groups:
//  1. kernel symbol (the "bpf_<name>" identifier)
//  2. helper id (decimal integer)
var helperDeclRegex = regexp.MustCompile(
	`^static\s+(?:[A-Za-z_][A-Za-z0-9_]*\s+)*` + // optional attrs / qualifiers / return-type words
		`(?:\*\s*)?` + // optional pointer return
		`\(\s*\*\s*const\s+(bpf_[A-Za-z0-9_]+)\s*\)` + // ( * const bpf_<name> )
		`\s*\([^)]*\)\s*=\s*\(\s*void\s*\*\s*\)\s*(\d+)\s*;`, // (params) = (void *) <id> ;
)

// ParseBPFHelperDefs walks the contents of libbpf's bpf_helper_defs.h and
// returns one LibbpfHelper per declaration, sorted by HelperID.
//
// The function is line-oriented: each `static ... = (void *) N;` line
// produces one entry. Comments (block / line), forward declarations
// (`struct foo;`), and includes are silently skipped. If the resulting
// helper set is empty an error is returned — every legitimate libbpf
// release ships dozens of declarations, so an empty parse always
// signals input corruption or a shape change we want to investigate.
func ParseBPFHelperDefs(src []byte) ([]LibbpfHelper, error) {
	if len(src) == 0 {
		return nil, fmt.Errorf("parse bpf_helper_defs.h: empty input")
	}

	cleaned := stripBlockComments(src)
	scanner := bufio.NewScanner(bytes.NewReader(cleaned))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	seen := make(map[string]int)
	var out []LibbpfHelper
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Fast filters — most lines in the header are blank,
		// comments, or forward declarations. The regex match below
		// is the source of truth; these are cheap fast-rejects.
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") || strings.HasPrefix(trimmed, "*") {
			continue
		}
		if !strings.HasPrefix(trimmed, "static") {
			continue
		}
		if !strings.Contains(trimmed, "(void *)") && !strings.Contains(trimmed, "(void*)") {
			// Could be the forward declarations block at the top
			// of the header — those start with "struct" but a
			// future shape we want to ignore. Skip safely.
			continue
		}

		matches := helperDeclRegex.FindStringSubmatch(trimmed)
		if matches == nil {
			// A static line that looks helper-shaped but doesn't
			// match the regex is worth surfacing — it means
			// upstream introduced a declaration shape the parser
			// doesn't understand, and the operator should
			// investigate.
			return nil, fmt.Errorf("parse bpf_helper_defs.h: unrecognized static declaration shape: %q", trimmed)
		}

		sym := matches[1]
		idStr := matches[2]
		id, err := strconv.Atoi(idStr)
		if err != nil {
			return nil, fmt.Errorf("parse bpf_helper_defs.h: helper %q has non-integer id %q", sym, idStr)
		}
		if id <= 0 {
			return nil, fmt.Errorf("parse bpf_helper_defs.h: helper %q has non-positive id %d", sym, id)
		}

		if prev, dup := seen[sym]; dup {
			return nil, fmt.Errorf("parse bpf_helper_defs.h: duplicate kernel symbol %q (first id=%d, second id=%d)", sym, prev, id)
		}
		seen[sym] = id

		out = append(out, LibbpfHelper{KernelSymbol: sym, HelperID: id})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("parse bpf_helper_defs.h: scan: %w", err)
	}

	if len(out) == 0 {
		return nil, fmt.Errorf("parse bpf_helper_defs.h: no helper declarations matched — header shape may have changed")
	}

	sort.Slice(out, func(i, j int) bool { return out[i].HelperID < out[j].HelperID })
	return out, nil
}

// stripBlockComments removes /* ... */ block comments from the input.
// Single-line // comments are left in place since the line scanner
// rejects them via the trimmed-prefix check. Block comments are
// stripped here because they can span lines and confuse the scanner.
func stripBlockComments(src []byte) []byte {
	var out bytes.Buffer
	out.Grow(len(src))

	i := 0
	for i < len(src) {
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '*' {
			// Find closing */
			end := bytes.Index(src[i+2:], []byte("*/"))
			if end == -1 {
				// Unterminated comment; consume rest of file.
				i = len(src)
				continue
			}
			// Preserve newlines inside the comment so line numbers
			// in any future diagnostic don't shift.
			for _, b := range src[i : i+2+end+2] {
				if b == '\n' {
					out.WriteByte('\n')
				}
			}
			i += 2 + end + 2
			continue
		}
		out.WriteByte(src[i])
		i++
	}
	return out.Bytes()
}
