/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <stdbool.h>
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

static __always_inline __u32 hzn_current_pid(void) {
    return (__u32)(bpf_get_current_pid_tgid() >> 32);
}

static __always_inline long hzn_current_comm(void *dst, __u32 size) {
    return bpf_get_current_comm(dst, size);
}

struct hzn_type_BatchEvent {
    __u32 pid;
    __u8 comm[16];
};
_Static_assert(sizeof(struct hzn_type_BatchEvent) == 20, "horizon: struct BatchEvent size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_BatchEvent, pid) == 0, "horizon: struct BatchEvent.pid offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_BatchEvent, comm) == 4, "horizon: struct BatchEvent.comm offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1 << 24);
} BatchEvents SEC(".maps");

static __always_inline struct hzn_type_BatchEvent *BatchEvents_reserve(void) {
    return bpf_ringbuf_reserve(&BatchEvents, sizeof(struct hzn_type_BatchEvent), 0);
}

static __always_inline void BatchEvents_submit(struct hzn_type_BatchEvent *value) {
    bpf_ringbuf_submit(value, 0);
}

static __always_inline bool hzn_fn_fillEvent(struct hzn_type_BatchEvent *ev, __u32 pid);

static __always_inline bool hzn_fn_fillEvent(struct hzn_type_BatchEvent *ev, __u32 pid) {
    ev->pid = pid;
    BatchEvents_submit(ev);
    return true;
}

SEC("tracepoint/sched/sched_process_exec")
int OnExec(struct trace_event_raw_sched_process_exec *ctx) {
    (void)ctx;
    struct hzn_type_BatchEvent *event = BatchEvents_reserve();
    if (event == 0) {
        return 0;
    }
    hzn_current_comm(&event->comm, sizeof(event->comm));
    hzn_fn_fillEvent(event, hzn_current_pid());
    return 0;
}
