/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

struct hzn_type_SockOpsEvent {
    __u32 op;
};
_Static_assert(sizeof(struct hzn_type_SockOpsEvent) == 4, "horizon: struct SockOpsEvent size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_SockOpsEvent, op) == 0, "horizon: struct SockOpsEvent.op offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1 << 24);
} SockOpsEvents SEC(".maps");

static __always_inline struct hzn_type_SockOpsEvent *SockOpsEvents_reserve(void) {
    return bpf_ringbuf_reserve(&SockOpsEvents, sizeof(struct hzn_type_SockOpsEvent), 0);
}

static __always_inline void SockOpsEvents_submit(struct hzn_type_SockOpsEvent *value) {
    bpf_ringbuf_submit(value, 0);
}

SEC("sockops")
int OnSockOps(struct bpf_sock_ops *ctx) {
    (void)ctx;
    struct hzn_type_SockOpsEvent *event = SockOpsEvents_reserve();
    if (event == 0) {
        return 0;
    }
    event->op = 0;
    SockOpsEvents_submit(event);
    return 0;
}
