// Code generated by hzn; DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"m31labs.dev/horizon/capability"
)

const CapabilityManifestJSON = "{\n  \"schema\": \"m31labs.dev/horizon/capability/v1\",\n  \"package\": \"probes\",\n  \"programs\": [\n    {\n      \"name\": \"ObserveTaskKill\",\n      \"kind\": \"lsm\",\n      \"attach\": \"task_kill\",\n      \"section\": \"lsm/task_kill\",\n      \"capabilities\": [\n        \"kernel.process.kill.observe\"\n      ]\n    }\n  ],\n  \"capabilities\": [\n    {\n      \"name\": \"kernel.process.kill.observe\",\n      \"kind\": \"source\",\n      \"danger\": {\n        \"mode\": \"observe\",\n        \"scope\": \"event\",\n        \"reversibility\": \"none\"\n      },\n      \"program\": \"ObserveTaskKill\",\n      \"section\": \"lsm/task_kill\",\n      \"maps\": {\n        \"read\": [],\n        \"write\": [],\n        \"events\": []\n      },\n      \"requirements\": {\n        \"min_kernel\": \"5.7\",\n        \"programs\": [\n          {\n            \"name\": \"lsm\",\n            \"min_kernel\": \"5.7\"\n          }\n        ],\n        \"permissions\": [\n          \"bpf_program_load\",\n          \"lsm_admin\"\n        ],\n        \"features\": [\n          \"bpf_lsm\"\n        ]\n      }\n    }\n  ],\n  \"requirements\": {\n    \"min_kernel\": \"5.7\",\n    \"programs\": [\n      {\n        \"name\": \"lsm\",\n        \"min_kernel\": \"5.7\"\n      }\n    ],\n    \"permissions\": [\n      \"bpf_program_load\",\n      \"lsm_admin\"\n    ],\n    \"features\": [\n      \"bpf_lsm\"\n    ]\n  }\n}\n"

func CapabilityManifest() (capability.Manifest, error) {
	var manifest capability.Manifest
	if err := json.Unmarshal([]byte(CapabilityManifestJSON), &manifest); err != nil {
		return capability.Manifest{}, err
	}
	return manifest, nil
}

type Objects struct {
	ObserveTaskKill *ebpf.Program `ebpf:"ObserveTaskKill"`
}

type LoadOptions struct {
	Collection    *ebpf.CollectionOptions
	RemoveMemlock bool
}

func LoadObjects(path string) (*Objects, error) {
	return LoadObjectsWithOptions(path, LoadOptions{RemoveMemlock: true})
}

func LoadObjectsWithOptions(path string, opts LoadOptions) (*Objects, error) {
	if opts.RemoveMemlock {
		if err := rlimit.RemoveMemlock(); err != nil {
			return nil, fmt.Errorf("remove memlock limit: %w", err)
		}
	}
	spec, err := ebpf.LoadCollectionSpec(path)
	if err != nil {
		return nil, fmt.Errorf("load %s: %w", path, err)
	}
	var objects Objects
	if err := spec.LoadAndAssign(&objects, opts.Collection); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}
	return &objects, nil
}

func (o *Objects) Close() error {
	if o == nil {
		return nil
	}
	var err error
	if o.ObserveTaskKill != nil {
		err = errors.Join(err, o.ObserveTaskKill.Close())
	}
	return err
}

func (o *Objects) AttachObserveTaskKill() (link.Link, error) {
	if o == nil || o.ObserveTaskKill == nil {
		return nil, fmt.Errorf("ObserveTaskKill program is not loaded")
	}
	return link.AttachLSM(link.LSMOptions{Program: o.ObserveTaskKill})
}
