/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

struct hzn_type_UretprobeExecEvent {
    __u32 pid;
};
_Static_assert(sizeof(struct hzn_type_UretprobeExecEvent) == 4, "horizon: struct UretprobeExecEvent size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_UretprobeExecEvent, pid) == 0, "horizon: struct UretprobeExecEvent.pid offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1 << 24);
} UretprobeExecEvents SEC(".maps");

static __always_inline struct hzn_type_UretprobeExecEvent *UretprobeExecEvents_reserve(void) {
    return bpf_ringbuf_reserve(&UretprobeExecEvents, sizeof(struct hzn_type_UretprobeExecEvent), 0);
}

static __always_inline void UretprobeExecEvents_submit(struct hzn_type_UretprobeExecEvent *value) {
    bpf_ringbuf_submit(value, 0);
}

SEC("uretprobe")
int OnExecReturn(struct pt_regs *ctx) {
    (void)ctx;
    struct hzn_type_UretprobeExecEvent *event = UretprobeExecEvents_reserve();
    if (event == 0) {
        return 0;
    }
    event->pid = 0;
    UretprobeExecEvents_submit(event);
    return 0;
}
