/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

static __always_inline __u32 hzn_current_pid(void) {
    return (__u32)(bpf_get_current_pid_tgid() >> 32);
}

static const __u64 hzn_const_FirstSeen = 1;

struct hzn_type_Count {
    __u64 seen;
};
_Static_assert(sizeof(struct hzn_type_Count) == 8, "horizon: struct Count size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_Count, seen) == 0, "horizon: struct Count.seen offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 1024);
    __type(key, __u32);
    __type(value, struct hzn_type_Count);
} ExecCounts SEC(".maps");

static __always_inline struct hzn_type_Count *ExecCounts_lookup(__u32 key) {
    return bpf_map_lookup_elem(&ExecCounts, &key);
}

static __always_inline long ExecCounts_update(__u32 key, struct hzn_type_Count value) {
    return bpf_map_update_elem(&ExecCounts, &key, &value, BPF_ANY);
}

SEC("tracepoint/sched/sched_process_exec")
int OnExec(struct trace_event_raw_sched_process_exec *ctx) {
    (void)ctx;
    __u32 pid = hzn_current_pid();
    struct hzn_type_Count *count = ExecCounts_lookup(pid);
    if (count == 0) {
        if (ExecCounts_update(pid, (struct hzn_type_Count){ .seen = hzn_const_FirstSeen }) != 0) {
            return 0;
        }
        return 0;
    }
    count->seen = count->seen + 1;
    return 0;
}
