// Code generated by hzn; DO NOT EDIT.

package bindings

import (
	"encoding/json"
	"errors"
	"fmt"
	"net"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"m31labs.dev/horizon/capability"
)

const CapabilityManifestJSON = "{\n  \"schema\": \"m31labs.dev/horizon/capability/v1\",\n  \"package\": \"probes\",\n  \"programs\": [\n    {\n      \"name\": \"DropTCP\",\n      \"kind\": \"xdp\",\n      \"attach\": \"\",\n      \"section\": \"xdp\",\n      \"capabilities\": [\n        \"kernel.network.xdp.drop\"\n      ]\n    }\n  ],\n  \"capabilities\": [\n    {\n      \"name\": \"kernel.network.xdp.drop\",\n      \"kind\": \"source\",\n      \"danger\": {\n        \"mode\": \"control\",\n        \"scope\": \"network\",\n        \"reversibility\": \"restart\"\n      },\n      \"program\": \"DropTCP\",\n      \"section\": \"xdp\",\n      \"maps\": {\n        \"read\": [],\n        \"write\": [],\n        \"events\": []\n      },\n      \"requirements\": {\n        \"min_kernel\": \"4.8\",\n        \"programs\": [\n          {\n            \"name\": \"xdp\",\n            \"min_kernel\": \"4.8\"\n          }\n        ],\n        \"permissions\": [\n          \"bpf_program_load\",\n          \"net_admin\"\n        ],\n        \"features\": [\n          \"netdev_xdp\"\n        ]\n      }\n    }\n  ],\n  \"requirements\": {\n    \"min_kernel\": \"4.8\",\n    \"programs\": [\n      {\n        \"name\": \"xdp\",\n        \"min_kernel\": \"4.8\"\n      }\n    ],\n    \"permissions\": [\n      \"bpf_program_load\",\n      \"net_admin\"\n    ],\n    \"features\": [\n      \"netdev_xdp\"\n    ]\n  }\n}\n"

func CapabilityManifest() (capability.Manifest, error) {
	var manifest capability.Manifest
	if err := json.Unmarshal([]byte(CapabilityManifestJSON), &manifest); err != nil {
		return capability.Manifest{}, err
	}
	return manifest, nil
}

type Objects struct {
	DropTCP *ebpf.Program `ebpf:"DropTCP"`
}

type LoadOptions struct {
	Collection    *ebpf.CollectionOptions
	RemoveMemlock bool
}

func LoadObjects(path string) (*Objects, error) {
	return LoadObjectsWithOptions(path, LoadOptions{RemoveMemlock: true})
}

func LoadObjectsWithOptions(path string, opts LoadOptions) (*Objects, error) {
	if opts.RemoveMemlock {
		if err := rlimit.RemoveMemlock(); err != nil {
			return nil, fmt.Errorf("remove memlock limit: %w", err)
		}
	}
	spec, err := ebpf.LoadCollectionSpec(path)
	if err != nil {
		return nil, fmt.Errorf("load %s: %w", path, err)
	}
	var objects Objects
	if err := spec.LoadAndAssign(&objects, opts.Collection); err != nil {
		return nil, fmt.Errorf("load eBPF objects: %w", err)
	}
	return &objects, nil
}

func (o *Objects) Close() error {
	if o == nil {
		return nil
	}
	var err error
	if o.DropTCP != nil {
		err = errors.Join(err, o.DropTCP.Close())
	}
	return err
}

func (o *Objects) AttachDropTCP(interfaceIndex int) (link.Link, error) {
	if o == nil || o.DropTCP == nil {
		return nil, fmt.Errorf("DropTCP program is not loaded")
	}
	return link.AttachXDP(link.XDPOptions{Program: o.DropTCP, Interface: interfaceIndex})
}

func (o *Objects) AttachDropTCPInterface(name string) (link.Link, error) {
	iface, err := net.InterfaceByName(name)
	if err != nil {
		return nil, err
	}
	return o.AttachDropTCP(iface.Index)
}
