/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

#include <bpf/bpf_endian.h>

#ifndef XDP_ABORTED
#define XDP_ABORTED 0
#define XDP_DROP 1
#define XDP_PASS 2
#define XDP_TX 3
#define XDP_REDIRECT 4
#endif

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

struct hzn_xdp_eth {
    __u8 dst[6];
    __u8 src[6];
    __u16 proto;
} __attribute__((packed));

struct hzn_xdp_ipv4 {
    __u8 version_ihl;
    __u8 tos;
    __u16 total_len;
    __u16 id;
    __u16 frag_off;
    __u8 ttl;
    __u8 protocol;
    __u16 check;
    __u32 src;
    __u32 dst;
} __attribute__((packed));

struct hzn_xdp_tcp {
    __u16 src_port;
    __u16 dst_port;
    __u32 seq;
    __u32 ack;
    __u8 data_off;
    __u8 flags;
    __u16 window;
    __u16 check;
    __u16 urg_ptr;
} __attribute__((packed));

struct hzn_xdp_udp {
    __u16 src_port;
    __u16 dst_port;
    __u16 len;
    __u16 check;
} __attribute__((packed));

static __always_inline struct hzn_xdp_eth *hzn_xdp_eth(struct xdp_md *ctx) {
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    if (data + sizeof(struct hzn_xdp_eth) > data_end) {
        return 0;
    }
    return data;
}

static __always_inline struct hzn_xdp_ipv4 *hzn_xdp_ipv4(struct xdp_md *ctx) {
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct hzn_xdp_eth *eth = hzn_xdp_eth(ctx);

    if (!eth || eth->proto != bpf_htons(0x0800)) {
        return 0;
    }

    void *ip = data + sizeof(struct hzn_xdp_eth);
    if (ip + sizeof(struct hzn_xdp_ipv4) > data_end) {
        return 0;
    }
    return ip;
}

static __always_inline __u64 hzn_xdp_l4_offset(struct xdp_md *ctx, __u8 protocol) {
    struct hzn_xdp_ipv4 *ip = hzn_xdp_ipv4(ctx);

    if (!ip || ip->protocol != protocol) {
        return 0;
    }

    __u8 ihl = ip->version_ihl & 0x0f;
    if (ihl < 5) {
        return 0;
    }
    return sizeof(struct hzn_xdp_eth) + ((__u64)ihl * 4);
}

static __always_inline struct hzn_xdp_tcp *hzn_xdp_tcp(struct xdp_md *ctx) {
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    __u64 off = hzn_xdp_l4_offset(ctx, 6);

    if (!off || data + off + sizeof(struct hzn_xdp_tcp) > data_end) {
        return 0;
    }
    return data + off;
}

SEC("xdp")
int DropTCP(struct xdp_md *ctx) {
    (void)ctx;
    struct hzn_xdp_tcp *tcp = hzn_xdp_tcp(ctx);
    if (tcp == 0) {
        return XDP_PASS;
    }
    switch (bpf_ntohs(tcp->dst_port)) {
        case 443:
        {
            return XDP_DROP;
            break;
        }
        default: {
            return XDP_PASS;
            break;
        }
    }
}
