/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

#include <bpf/bpf_endian.h>

#ifndef HZN_CGROUP_DENY
#define HZN_CGROUP_DENY 0
#define HZN_CGROUP_ALLOW 1
#endif
#ifndef HZN_CGROUP_FAMILY_IPV4
#define HZN_CGROUP_FAMILY_IPV4 2
#define HZN_CGROUP_FAMILY_IPV6 10
#define HZN_CGROUP_SOCK_STREAM 1
#define HZN_CGROUP_SOCK_DGRAM 2
#define HZN_CGROUP_PROTOCOL_TCP 6
#define HZN_CGROUP_PROTOCOL_UDP 17
#endif

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

static __always_inline __u32 hzn_cgroup_family(struct bpf_sock_addr *ctx) {
    return ctx->family;
}

static __always_inline __u32 hzn_cgroup_protocol(struct bpf_sock_addr *ctx) {
    return ctx->protocol;
}

static __always_inline __u16 hzn_cgroup_dst_port(struct bpf_sock_addr *ctx) {
    return bpf_ntohs((__u16)ctx->user_port);
}

static __always_inline __u32 hzn_cgroup_dst_ip4(struct bpf_sock_addr *ctx) {
    return bpf_ntohl(ctx->user_ip4);
}

SEC("cgroup/connect4")
int BlockSMTP(struct bpf_sock_addr *ctx) {
    (void)ctx;
    if (hzn_cgroup_family(ctx) != HZN_CGROUP_FAMILY_IPV4) {
        return HZN_CGROUP_ALLOW;
    }
    if (hzn_cgroup_protocol(ctx) != HZN_CGROUP_PROTOCOL_TCP) {
        return HZN_CGROUP_ALLOW;
    }
    if ((hzn_cgroup_dst_port(ctx) == 25) && (hzn_cgroup_dst_ip4(ctx) != (((__u32)(127) << 24) | ((__u32)(0) << 16) | ((__u32)(0) << 8) | (__u32)(1)))) {
        return HZN_CGROUP_DENY;
    }
    return HZN_CGROUP_ALLOW;
}
