/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

static __always_inline __u32 hzn_current_pid(void) {
    return (__u32)(bpf_get_current_pid_tgid() >> 32);
}

static __always_inline __u32 hzn_current_uid(void) {
    return (__u32)bpf_get_current_uid_gid();
}

static __always_inline long hzn_current_comm(void *dst, __u32 size) {
    return bpf_get_current_comm(dst, size);
}

struct hzn_type_TCPConnectEvent {
    __u32 pid;
    __u32 uid;
    __u8 comm[16];
};
_Static_assert(sizeof(struct hzn_type_TCPConnectEvent) == 24, "horizon: struct TCPConnectEvent size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_TCPConnectEvent, pid) == 0, "horizon: struct TCPConnectEvent.pid offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_TCPConnectEvent, uid) == 4, "horizon: struct TCPConnectEvent.uid offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_TCPConnectEvent, comm) == 8, "horizon: struct TCPConnectEvent.comm offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1 << 24);
} TCPConnectEvents SEC(".maps");

static __always_inline struct hzn_type_TCPConnectEvent *TCPConnectEvents_reserve(void) {
    return bpf_ringbuf_reserve(&TCPConnectEvents, sizeof(struct hzn_type_TCPConnectEvent), 0);
}

static __always_inline void TCPConnectEvents_submit(struct hzn_type_TCPConnectEvent *value) {
    bpf_ringbuf_submit(value, 0);
}

SEC("kprobe/tcp_v4_connect")
int OnTCPConnect(struct pt_regs *ctx) {
    (void)ctx;
    struct hzn_type_TCPConnectEvent *event = TCPConnectEvents_reserve();
    if (event == 0) {
        return 0;
    }
    event->pid = hzn_current_pid();
    event->uid = hzn_current_uid();
    hzn_current_comm(&event->comm, sizeof(event->comm));
    TCPConnectEvents_submit(event);
    return 0;
}
