/* Code generated by hzn; DO NOT EDIT. */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

_Static_assert(sizeof(__u8) == 1, "horizon: __u8 width mismatch");
_Static_assert(sizeof(__u16) == 2, "horizon: __u16 width mismatch");
_Static_assert(sizeof(__u32) == 4, "horizon: __u32 width mismatch");
_Static_assert(sizeof(__u64) == 8, "horizon: __u64 width mismatch");
_Static_assert(sizeof(__s8) == 1, "horizon: __s8 width mismatch");
_Static_assert(sizeof(__s16) == 2, "horizon: __s16 width mismatch");
_Static_assert(sizeof(__s32) == 4, "horizon: __s32 width mismatch");
_Static_assert(sizeof(__s64) == 8, "horizon: __s64 width mismatch");

static __always_inline __u32 hzn_current_pid(void) {
    return (__u32)(bpf_get_current_pid_tgid() >> 32);
}

static __always_inline __u32 hzn_current_uid(void) {
    return (__u32)bpf_get_current_uid_gid();
}

static __always_inline long hzn_current_comm(void *dst, __u32 size) {
    return bpf_get_current_comm(dst, size);
}

static __always_inline long hzn_probe_read_user_str(void *dst, __u32 size, const void *unsafe_ptr) {
    return bpf_probe_read_user_str(dst, size, unsafe_ptr);
}

static __always_inline __u64 hzn_kprobe_arg2(struct pt_regs *ctx) {
    return (__u64)PT_REGS_PARM2(ctx);
}

struct hzn_type_OpenEvent {
    __u32 pid;
    __u32 uid;
    __u8 comm[16];
    __u8 path[256];
};
_Static_assert(sizeof(struct hzn_type_OpenEvent) == 280, "horizon: struct OpenEvent size mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_OpenEvent, pid) == 0, "horizon: struct OpenEvent.pid offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_OpenEvent, uid) == 4, "horizon: struct OpenEvent.uid offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_OpenEvent, comm) == 8, "horizon: struct OpenEvent.comm offset mismatch");
_Static_assert(__builtin_offsetof(struct hzn_type_OpenEvent, path) == 24, "horizon: struct OpenEvent.path offset mismatch");

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 1 << 24);
} OpenEvents SEC(".maps");

static __always_inline struct hzn_type_OpenEvent *OpenEvents_reserve(void) {
    return bpf_ringbuf_reserve(&OpenEvents, sizeof(struct hzn_type_OpenEvent), 0);
}

static __always_inline void OpenEvents_submit(struct hzn_type_OpenEvent *value) {
    bpf_ringbuf_submit(value, 0);
}

static __always_inline void OpenEvents_discard(struct hzn_type_OpenEvent *value) {
    bpf_ringbuf_discard(value, 0);
}

SEC("kprobe/do_sys_openat2")
int OnOpen(struct pt_regs *ctx) {
    (void)ctx;
    struct hzn_type_OpenEvent *event = OpenEvents_reserve();
    if (event == 0) {
        return 0;
    }
    event->pid = hzn_current_pid();
    event->uid = hzn_current_uid();
    hzn_current_comm(&event->comm, sizeof(event->comm));
    if (hzn_probe_read_user_str(&event->path, sizeof(event->path), (const void *)(long)hzn_kprobe_arg2(ctx)) < 0) {
        OpenEvents_discard(event);
        return 0;
    }
    OpenEvents_submit(event);
    return 0;
}
